version: '3'

services:
  backend:
    container_name: server
    image: node:12.17.0-alpine
    command: yarn start
    volumes:
      - ./server:/server
    working_dir: /server
    ports:
      - 3333:3333
    tty: true
    stdin_open: true
  web:
      container_name: web
      image: node:12.18.3-alpine
      volumes:
        - ./web:/web
      working_dir: /web
      command: yarn start
      ports:
        - 80:3000
      tty: true
      stdin_open: true